version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: monthly
      day: 'sunday'
      time: '08:00'
      timezone: Asia/Saigon
    versioning-strategy: increase-if-necessary
    target-branch: 'main'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    commit-message:
      prefix: 'npm'
      prefix-development: 'bump'
      include: 'scope'
    assignees:
      - harrytran998
